### ISSUE TITLE
Getting Started with git

### ISSUE THREAD

**Issue by mahmud2011** [SOFTowaha/studyGroup#6]
**Event Name:** Getting Started with git

**Time:** 15:30 HH
**Date:** 09 Aug 2015
**Location:** ACL Lab, Metropolitan University, Sylhet, Bangladesh. [Map](https://www.google.com.bd/maps/place/Metropolitan+University/@24.89721,91.8676114,17z/data=!3m1!4b1!4m2!3m1!1s0x3750552bc71c899d:0x804e438bcc32b390?hl=en)

**Speaker:** [Md. Shahjahan Jewel](https://mozillians.org/en-US/u/cep.jewel/), Head of Ideas, Technext Limited. 
**Organizer:** [Firefox Club MU](https://wiki.mozilla.org/Firefox_Club_MU)

**Topics:** 
1. git basics 
2. git command line
3. Github

**Perquisite:** 
1. git installed on participants laptops
2. Github Account.

**Registration:**  http://www.eventbrite.com/e/getting-started-with-git-tickets-18050891703

**Comment by SOFTowaha** [comment]
I'm adding this on the git side.

**Comment by SOFTowaha** [comment]
@mmhyamin please add some descriptionss of the event.

**Comment by mahmud2011** [comment]
Participants will be acknowledged about Git
